--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    whatsapp text,
    city text,
    birthday date,
    preferences text,
    allergies_or_needs text,
    business_lines_interest text[]
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.appointments (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text not null,
    status text not null,
    scheduled_at timestamp with time zone not null,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.catalog_links (
    id bigint generated by default as identity primary key,
    title text not null,
    url text not null,
    type text not null default 'link',
    business_line text,
    campaign text,
    active boolean not null default true,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.customer_events (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    business_line_id bigint,
    type text not null,
    occurred_at timestamp with time zone not null default now(),
    payload jsonb not null default '{}'::jsonb,
    source text not null default 'system',
    sales_id bigint,
    related_table text,
    related_id bigint,
    created_at timestamp with time zone not null default now()
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.appointments
    add constraint appointments_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.catalog_links
    add constraint catalog_links_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete set null;

alter table public.customer_events
    add constraint customer_events_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.customer_events
    add constraint customer_events_business_line_id_fkey foreign key (business_line_id) references public.companies(id) on update cascade on delete set null;

alter table public.customer_events
    add constraint customer_events_sales_id_fkey foreign key (sales_id) references public.sales(id) on update cascade on delete set null;

alter table public.catalog_links
    add constraint catalog_links_type_check
    check (type in ('catalog', 'link', 'campaign', 'promotion'));

alter table public.catalog_links
    add constraint catalog_links_business_line_check
    check (
        business_line is null
        or business_line in ('mary-kay', 'beyond-beauty', 'incruises')
    );

alter table public.customer_events
    add constraint customer_events_type_check check (
        type = any (
            array[
                'note.created'::text,
                'task.created'::text,
                'task.completed'::text,
                'appointment.created'::text,
                'appointment.completed'::text,
                'appointment.cancelled'::text,
                'opportunity.created'::text,
                'opportunity.stage_changed'::text,
                'note.updated'::text,
                'whatsapp.opened'::text,
                'session.opened'::text,
                'email.sent'::text,
                'task.snoozed'::text,
                'opportunity.won'::text,
                'opportunity.lost'::text,
                'order.created'::text,
                'order.paid'::text,
                'order.delivered'::text,
                'catalog.shared'::text,
                'birthday.celebrated'::text,
                'reactivation.attempted'::text
            ]
        )
    );

alter table public.customer_events
    add constraint customer_events_source_check check (
        source = any (
            array[
                'manual'::text,
                'system'::text,
                'calendar_sync'::text,
                'csv_import'::text,
                'whatsapp_link'::text,
                'app_launch'::text
            ]
        )
    );

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
create index appointments_contact_id_idx on public.appointments using btree (contact_id);
create index catalog_links_business_line_idx on public.catalog_links using btree (business_line);
create index catalog_links_active_idx on public.catalog_links using btree (active);
create index catalog_links_type_idx on public.catalog_links using btree (type);
create index customer_events_contact_id_occurred_at_idx on public.customer_events using btree (contact_id, occurred_at desc);
create index customer_events_contact_id_idx on public.customer_events using btree (contact_id);
create index customer_events_type_occurred_at_idx on public.customer_events using btree (type, occurred_at desc);
create index customer_events_business_line_id_idx on public.customer_events using btree (business_line_id) where business_line_id is not null;
create index customer_events_related_record_idx on public.customer_events using btree (related_table, related_id) where related_id is not null;
create index customer_events_sales_id_occurred_at_idx on public.customer_events using btree (sales_id, occurred_at desc) where sales_id is not null;
