create table if not exists public.catalog_links (
    id bigint generated by default as identity primary key,
    title text not null,
    url text not null,
    type text not null default 'link',
    business_line text,
    campaign text,
    active boolean not null default true,
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.catalog_links
    add constraint catalog_links_type_check
    check (type in ('catalog', 'link', 'campaign', 'promotion'));

alter table public.catalog_links
    add constraint catalog_links_business_line_check
    check (
        business_line is null
        or business_line in ('mary-kay', 'beyond-beauty', 'incruises')
    );

alter table public.catalog_links
    add constraint catalog_links_sales_id_fkey
    foreign key (sales_id) references public.sales(id)
    on update cascade on delete set null;

create index if not exists catalog_links_business_line_idx
    on public.catalog_links using btree (business_line);

create index if not exists catalog_links_active_idx
    on public.catalog_links using btree (active);

create index if not exists catalog_links_type_idx
    on public.catalog_links using btree (type);

alter table public.catalog_links enable row level security;

create policy "Enable read access for authenticated users"
    on public.catalog_links for select to authenticated using (true);

create policy "Enable insert for authenticated users only"
    on public.catalog_links for insert to authenticated with check (true);

create policy "Catalog Link Update Policy"
    on public.catalog_links for update to authenticated using (true);

create policy "Catalog Link Delete Policy"
    on public.catalog_links for delete to authenticated using (true);
