-- ============================================================================
-- customer_events — append-only timeline backbone
-- ============================================================================
-- Cada fila representa UN evento de relación con una clienta.
-- Esta tabla alimenta:
--   1. Timeline unificado por clienta (vista "todo lo que pasó con Laura")
--   2. Pantalla "Hoy" (qué requiere acción)
--   3. Cohortes (clientas sin contacto >30 días, etc.)
--   4. Auditoría e histórico operativo
--
-- Reglas:
--   * Append-only (no updates ni deletes en lógica de aplicación)
--   * Una fila por evento atómico
--   * payload jsonb para datos específicos del tipo
--   * Triggers desde contact_notes, tasks, appointments, deals la alimentan
--
-- PREREQUISITOS (deben aplicarse antes que esta migración):
--   * 20260516183000_contact_profile_fields.sql (birthday, whatsapp, business_lines_interest)
--   * 20260516201500_appointments_entity.sql    (tabla appointments)
-- El trigger de appointments y el backfill de appointments se ejecutan
-- condicionalmente si la tabla existe, así que esta migración es defensiva.
-- ============================================================================

create table if not exists public.customer_events (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    business_line_id bigint,
    type text not null,
    occurred_at timestamp with time zone not null default now(),
    payload jsonb not null default '{}'::jsonb,
    source text not null default 'system',
    sales_id bigint,
    related_table text,
    related_id bigint,
    created_at timestamp with time zone not null default now()
);

-- ----------------------------------------------------------------------------
-- Foreign keys
-- ----------------------------------------------------------------------------

alter table public.customer_events
    add constraint customer_events_contact_id_fkey
    foreign key (contact_id) references public.contacts(id)
    on update cascade on delete cascade;

-- business_line_id apunta a companies (reinterpretadas como líneas de negocio
-- en el dominio Claridad). Se permite null porque hay eventos sin línea.
alter table public.customer_events
    add constraint customer_events_business_line_id_fkey
    foreign key (business_line_id) references public.companies(id)
    on update cascade on delete set null;

alter table public.customer_events
    add constraint customer_events_sales_id_fkey
    foreign key (sales_id) references public.sales(id)
    on update cascade on delete set null;

-- ----------------------------------------------------------------------------
-- Constraints
-- ----------------------------------------------------------------------------

-- Tipos válidos. Añadir nuevos tipos requiere migración explícita.
alter table public.customer_events
    add constraint customer_events_type_check
    check (type in (
        -- Tipos activos v1
        'note.created',
        'task.created',
        'task.completed',
        'appointment.created',
        'appointment.completed',
        'appointment.cancelled',
        'opportunity.created',
        'opportunity.stage_changed',
        -- Tipos reservados para fases posteriores
        'note.updated',
        'whatsapp.opened',
        'session.opened',
        'email.sent',
        'task.snoozed',
        'opportunity.won',
        'opportunity.lost',
        'order.created',
        'order.paid',
        'order.delivered',
        'catalog.shared',
        'birthday.celebrated',
        'reactivation.attempted'
    ));

-- Fuente del evento. Útil para distinguir manuales, sistema, sync, importación.
alter table public.customer_events
    add constraint customer_events_source_check
    check (source in (
        'manual',
        'system',
        'calendar_sync',
        'csv_import',
        'whatsapp_link',
        'app_launch'
    ));

-- ----------------------------------------------------------------------------
-- Indexes
-- ----------------------------------------------------------------------------

-- Timeline por clienta (query más frecuente)
create index if not exists customer_events_contact_id_occurred_at_idx
    on public.customer_events using btree (contact_id, occurred_at desc);

-- "Última actividad por clienta" (cohorte de reactivación)
create index if not exists customer_events_contact_id_idx
    on public.customer_events using btree (contact_id);

-- Filtros por tipo (e.g. listar todos los whatsapp.opened de la semana)
create index if not exists customer_events_type_occurred_at_idx
    on public.customer_events using btree (type, occurred_at desc);

-- Filtros por línea de negocio
create index if not exists customer_events_business_line_id_idx
    on public.customer_events using btree (business_line_id)
    where business_line_id is not null;

create index if not exists customer_events_related_record_idx
    on public.customer_events using btree (related_table, related_id)
    where related_id is not null;

create index if not exists customer_events_sales_id_occurred_at_idx
    on public.customer_events using btree (sales_id, occurred_at desc)
    where sales_id is not null;

-- ----------------------------------------------------------------------------
-- Row Level Security
-- ----------------------------------------------------------------------------

alter table public.customer_events enable row level security;

create policy "customer_events read for authenticated"
    on public.customer_events for select
    to authenticated
    using (true);

create policy "customer_events insert for authenticated"
    on public.customer_events for insert
    to authenticated
    with check (true);

-- NO se crean policies de UPDATE ni DELETE intencionalmente.
-- La tabla es append-only desde la perspectiva de la aplicación.
-- Para corregir eventos erróneos, insertar un evento compensatorio.

-- ----------------------------------------------------------------------------
-- Triggers: alimentar customer_events desde tablas existentes
-- ----------------------------------------------------------------------------

-- Función genérica para resolver business_line_id desde un contact_id
create or replace function public.resolve_business_line_from_contact(p_contact_id bigint)
returns bigint
language sql
stable
security invoker
set search_path = public
as $$
    select company_id from public.contacts where id = p_contact_id
$$;

-- ---- contact_notes → note.created ----
create or replace function public.tg_customer_events_from_contact_note()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    insert into public.customer_events (
        contact_id,
        business_line_id,
        type,
        occurred_at,
        payload,
        source,
        sales_id,
        related_table,
        related_id
    )
    values (
        new.contact_id,
        public.resolve_business_line_from_contact(new.contact_id),
        'note.created',
        coalesce(new.date, now()),
        jsonb_build_object(
            'preview', left(coalesce(new.text, ''), 200),
            'status', new.status
        ),
        'system',
        new.sales_id,
        'contact_notes',
        new.id
    );
    return new;
end;
$$;

create trigger customer_events_from_contact_note
    after insert on public.contact_notes
    for each row
    execute function public.tg_customer_events_from_contact_note();

-- ---- tasks → task.created / task.completed ----
create or replace function public.tg_customer_events_from_task()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    if (TG_OP = 'INSERT') then
        insert into public.customer_events (
            contact_id, business_line_id, type, occurred_at, payload,
            source, sales_id, related_table, related_id
        )
        values (
            new.contact_id,
            public.resolve_business_line_from_contact(new.contact_id),
            'task.created',
            coalesce(new.due_date, now()),
            jsonb_build_object(
                'title', new.text,
                'due_date', new.due_date,
                'type', new.type
            ),
            'system',
            new.sales_id,
            'tasks',
            new.id
        );
    elsif (TG_OP = 'UPDATE'
           and old.done_date is null
           and new.done_date is not null) then
        insert into public.customer_events (
            contact_id, business_line_id, type, occurred_at, payload,
            source, sales_id, related_table, related_id
        )
        values (
            new.contact_id,
            public.resolve_business_line_from_contact(new.contact_id),
            'task.completed',
            new.done_date,
            jsonb_build_object('title', new.text),
            'system',
            new.sales_id,
            'tasks',
            new.id
        );
    end if;
    return new;
end;
$$;

create trigger customer_events_from_task
    after insert or update on public.tasks
    for each row
    execute function public.tg_customer_events_from_task();

-- ---- appointments → appointment.created / completed / cancelled ----
create or replace function public.tg_customer_events_from_appointment()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    if (TG_OP = 'INSERT') then
        insert into public.customer_events (
            contact_id, business_line_id, type, occurred_at, payload,
            source, related_table, related_id
        )
        values (
            new.contact_id,
            public.resolve_business_line_from_contact(new.contact_id),
            case new.status
                when 'completed' then 'appointment.completed'
                when 'cancelled' then 'appointment.cancelled'
                else 'appointment.created'
            end,
            new.scheduled_at,
            jsonb_build_object(
                'type', new.type,
                'status', new.status,
                'scheduled_at', new.scheduled_at
            ),
            'system',
            'appointments',
            new.id
        );
    elsif (
        TG_OP = 'UPDATE'
        and old.status is distinct from new.status
        and new.status in ('completed', 'cancelled')
    ) then
        insert into public.customer_events (
            contact_id, business_line_id, type, occurred_at, payload,
            source, related_table, related_id
        )
        values (
            new.contact_id,
            public.resolve_business_line_from_contact(new.contact_id),
            case new.status
                when 'completed' then 'appointment.completed'
                else 'appointment.cancelled'
            end,
            coalesce(new.updated_at, now()),
            jsonb_build_object(
                'type', new.type,
                'status', new.status,
                'scheduled_at', new.scheduled_at
            ),
            'system',
            'appointments',
            new.id
        );
    end if;

    return new;
end;
$$;

do $$
begin
    if exists (
        select 1
        from information_schema.tables
        where table_schema = 'public'
          and table_name = 'appointments'
    ) then
        execute 'drop trigger if exists customer_events_from_appointment on public.appointments';
        execute 'create trigger customer_events_from_appointment
                 after insert or update on public.appointments
                 for each row
                 execute function public.tg_customer_events_from_appointment()';
    else
        raise notice 'Tabla public.appointments no existe - trigger de appointments OMITIDO. Aplicar 20260516201500_appointments_entity.sql primero.';
    end if;
end $$;

-- ---- deals → opportunity.created / opportunity.stage_changed ----
-- Nota: deals están reinterpretados como "opportunities" en Claridad.
-- Como deals.contact_ids es un array, escribimos un evento por cada contacto.
create or replace function public.tg_customer_events_from_deal()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_contact_id bigint;
begin
    if (TG_OP = 'INSERT') then
        if new.contact_ids is not null then
            foreach v_contact_id in array new.contact_ids loop
                insert into public.customer_events (
                    contact_id, business_line_id, type, occurred_at, payload,
                    source, sales_id, related_table, related_id
                )
                values (
                    v_contact_id,
                    new.company_id,
                    'opportunity.created',
                    coalesce(new.created_at, now()),
                    jsonb_build_object(
                        'name', new.name,
                        'stage', new.stage,
                        'amount', new.amount
                    ),
                    'system',
                    new.sales_id,
                    'deals',
                    new.id
                );
            end loop;
        end if;
    elsif (TG_OP = 'UPDATE' and old.stage is distinct from new.stage) then
        if new.contact_ids is not null then
            foreach v_contact_id in array new.contact_ids loop
                insert into public.customer_events (
                    contact_id, business_line_id, type, occurred_at, payload,
                    source, sales_id, related_table, related_id
                )
                values (
                    v_contact_id,
                    new.company_id,
                    'opportunity.stage_changed',
                    now(),
                    jsonb_build_object(
                        'name', new.name,
                        'from_stage', old.stage,
                        'to_stage', new.stage
                    ),
                    'system',
                    new.sales_id,
                    'deals',
                    new.id
                );
            end loop;
        end if;
    end if;
    return new;
end;
$$;

create trigger customer_events_from_deal
    after insert or update on public.deals
    for each row
    execute function public.tg_customer_events_from_deal();

-- ----------------------------------------------------------------------------
-- Backfill: poblar customer_events desde datos existentes
-- ----------------------------------------------------------------------------

-- Notas existentes
insert into public.customer_events (
    contact_id, business_line_id, type, occurred_at, payload,
    source, sales_id, related_table, related_id
)
select
    cn.contact_id,
    c.company_id,
    'note.created',
    coalesce(cn.date, now()),
    jsonb_build_object(
        'preview', left(coalesce(cn.text, ''), 200),
        'status', cn.status
    ),
    'system',
    cn.sales_id,
    'contact_notes',
    cn.id
from public.contact_notes cn
left join public.contacts c on c.id = cn.contact_id
where not exists (
    select 1
    from public.customer_events ce
    where ce.related_table = 'contact_notes'
      and ce.related_id = cn.id
      and ce.type = 'note.created'
)
on conflict do nothing;

-- Tareas creadas existentes
insert into public.customer_events (
    contact_id, business_line_id, type, occurred_at, payload,
    source, sales_id, related_table, related_id
)
select
    t.contact_id,
    c.company_id,
    'task.created',
    -- tasks no tiene created_at en el esquema base de Atomic;
    -- usamos due_date como aproximación o now() si es null.
    coalesce(t.due_date, now()),
    jsonb_build_object(
        'title', t.text,
        'due_date', t.due_date,
        'type', t.type
    ),
    'system',
    t.sales_id,
    'tasks',
    t.id
from public.tasks t
left join public.contacts c on c.id = t.contact_id
where not exists (
    select 1
    from public.customer_events ce
    where ce.related_table = 'tasks'
      and ce.related_id = t.id
      and ce.type = 'task.created'
)
on conflict do nothing;

-- Tareas ya completadas
insert into public.customer_events (
    contact_id, business_line_id, type, occurred_at, payload,
    source, sales_id, related_table, related_id
)
select
    t.contact_id,
    c.company_id,
    'task.completed',
    t.done_date,
    jsonb_build_object('title', t.text),
    'system',
    t.sales_id,
    'tasks',
    t.id
from public.tasks t
left join public.contacts c on c.id = t.contact_id
where t.done_date is not null
  and not exists (
      select 1
      from public.customer_events ce
      where ce.related_table = 'tasks'
        and ce.related_id = t.id
        and ce.type = 'task.completed'
  )
on conflict do nothing;

-- Citas existentes (condicional: solo si la tabla appointments existe)
do $$
begin
    if exists (
        select 1
        from information_schema.tables
        where table_schema = 'public'
          and table_name = 'appointments'
    ) then
        execute $sql$
            insert into public.customer_events (
                contact_id, business_line_id, type, occurred_at, payload,
                source, related_table, related_id
            )
            select
                a.contact_id,
                c.company_id,
                case a.status
                    when 'completed' then 'appointment.completed'
                    when 'cancelled' then 'appointment.cancelled'
                    else 'appointment.created'
                end,
                a.scheduled_at,
                jsonb_build_object(
                    'type', a.type,
                    'status', a.status,
                    'scheduled_at', a.scheduled_at
                ),
                'system',
                'appointments',
                a.id
            from public.appointments a
            left join public.contacts c on c.id = a.contact_id
            where not exists (
                select 1
                from public.customer_events ce
                where ce.related_table = 'appointments'
                  and ce.related_id = a.id
                  and ce.type = case a.status
                    when 'completed' then 'appointment.completed'
                    when 'cancelled' then 'appointment.cancelled'
                    else 'appointment.created'
                  end
            )
            on conflict do nothing
        $sql$;
    end if;
end $$;

-- Oportunidades (deals) existentes
insert into public.customer_events (
    contact_id, business_line_id, type, occurred_at, payload,
    source, sales_id, related_table, related_id
)
select
    unnest(d.contact_ids) as contact_id,
    d.company_id,
    'opportunity.created',
    coalesce(d.created_at, now()),
    jsonb_build_object(
        'name', d.name,
        'stage', d.stage,
        'amount', d.amount
    ),
    'system',
    d.sales_id,
    'deals',
    d.id
from public.deals d
where d.contact_ids is not null and array_length(d.contact_ids, 1) > 0
  and not exists (
      select 1
      from public.customer_events ce
      where ce.related_table = 'deals'
        and ce.related_id = d.id
        and ce.type = 'opportunity.created'
  )
on conflict do nothing;

-- ============================================================================
-- FIN — customer_events
-- ============================================================================
