create table if not exists public.appointments (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text not null,
    status text not null,
    scheduled_at timestamp with time zone not null,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.appointments
    add constraint appointments_contact_id_fkey
    foreign key (contact_id) references public.contacts(id)
    on update cascade on delete cascade;

create index if not exists appointments_contact_id_idx
    on public.appointments using btree (contact_id);

alter table public.appointments enable row level security;

create policy "Enable read access for authenticated users"
    on public.appointments for select to authenticated using (true);

create policy "Enable insert for authenticated users only"
    on public.appointments for insert to authenticated with check (true);

create policy "Appointment Update Policy"
    on public.appointments for update to authenticated using (true);

create policy "Appointment Delete Policy"
    on public.appointments for delete to authenticated using (true);
